### ISSUE TITLE
Improving login.html by adding css in it

### ISSUE THREAD

**Issue by Vidip-Ghosh** [jimmy-byte/-HactoberFest2023-For_All_Beginers-#344]
Restructuring the UI of Javascript Login Form Validation. Adding features like if the field remains empty, it throws an error. 

*Before:*
<img width="1680" alt="Screenshot 2022-10-12 at 20 01 08" src="https://user-images.githubusercontent.com/91741581/195384717-8320a961-8368-43fe-af4b-3130e0f49dfa.png">

*After:*
<img width="1680" alt="Screenshot 2022-10-12 at 20 54 31" src="https://user-images.githubusercontent.com/91741581/195384823-12e2a596-5e8c-403d-84f7-7091652e5647.png">

**Comment by 120EE0980** [comment]
Can u assign this issue to me..

**Comment by to-program-khushi-jain** [comment]
Hello, Can you assign this issue to me?
thanks.

**Comment by KashishRathore** [comment]
Hello, I'm good in css. Can you assign this issue to me?

**Comment by Vidip-Ghosh** [comment]
You all can try this. 
Since I am not an admin, I can’t assign.

**Comment by GeeteshMehto** [comment]
Hello sir can yo please assign this issue to me

**Comment by Deepanshu1008** [comment]
Can you assign this issue to me?

**Comment by princehabeeb** [comment]
I will like to handle this. can you please assign this to me?

**Comment by unovajnv** [comment]
hii  sir , can you please assign it to me i have good knowldge of css , i will make it more intractive.

**Comment by smitahub** [comment]
hello sir, please assign me this issues.

**Comment by sonam08082004** [comment]
Hello sir , can you please assign this issue to me , I am able to make this page attractive as I have good knowledge of css.

**Comment by vinay1033** [comment]
Can I add css to your login.html for beautiful interface.
