### ISSUE TITLE
Loading Bar

### ISSUE THREAD

**Issue by Abdulwahid7027** [jimmy-byte/-HactoberFest2023-For_All_Beginers-#550]
A while back, I created an Loading Bar that I think could be helpful for beginners working in frontend development, especially in vanilla JavaScript. I'm interested in contributing this project to Hacktoberfest and adding it to this repository. Please let me know if this is something you're interested in.

[project link](https://github.com/Abdulwahid7027/Frontend-Mini-Projects/tree/main/Loading%20Bar)

![Loading Bar](https://github.com/jimmy-byte/-HactoberFest2023-For_All_Beginers-/assets/110891341/149f38ef-7bd9-4884-a1a8-5aaf873758ec)

**Comment by sonupachauri02** [comment]
Please Assign it to me, I can do this as per your demand.
