### ISSUE TITLE
Check_Prime_number

### ISSUE THREAD

**Issue by paulsuryanshu** [jimmy-byte/-HactoberFest2023-For_All_Beginers-#637]
This made by c programming language...

**Comment by mrinalproxy** [comment]
assigned this issue to me

**Comment by 786-aquib** [comment]
!assign

**Comment by Shimrangupta22** [comment]
assigned it to me please

**Comment by Shimrangupta22** [comment]
hello ...why is my name not showing in the assigned options

**Comment by Mohd786-hub** [comment]
assign this to me .i will do this code using better algorithm and better time complexity
