### ISSUE TITLE
Creating a particles cursor with html css 

### ISSUE THREAD

**Issue by VinayakChaurasia007** [jimmy-byte/-HactoberFest2023-For_All_Beginers-#706]
Creating an Html css page with cursor animated such that when it moves , a particles animation should appear with its motion.

**Comment by VinayakChaurasia007** [comment]
Hello sir can you assign this issue to me

**Comment by RahulSoni2532** [comment]
I can make the custom cursor for you kindly assign me this @jimmy-byte

**Comment by Ashima2003** [comment]
Hey Please assign me this issue. I want to work on it.
